# Generated by Django 3.1.6 on 2021-02-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
