# Generated by Django 3.1.6 on 2021-02-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapists', '0003_auto_20210216_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='therapist',
            name='airtable_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
