# Generated by Django 3.1.6 on 2021-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapists', '0004_auto_20210217_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='airtable_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
