# Generated by Django 3.1.6 on 2021-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapists', '0005_therapist_airtable_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='airtable_modified',
            field=models.DateTimeField(),
        ),
    ]
