# Generated by Django 3.1.6 on 2021-02-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapists', '0006_auto_20210217_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtableRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', models.TextField()),
            ],
        ),
    ]
