# Generated by Django 3.1.6 on 2021-02-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapists', '0007_airtableraw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtableraw',
            options={'verbose_name': 'airtable data', 'verbose_name_plural': 'Airtable Raw Data'},
        ),
    ]
